Add developer shell for Rust programming language
input-output-hk/devx pull request #20
Opened 2023-01-15 18:08 UTC by yvan-sraka

https://www.rust-lang.org

2023-03-10 05:20 UTC, angerman commented on fix-devshells.nix
> +# second example) to work with `nix develop`!
```suggestion
# The following code will therefore transform an attribute set of the form
#    { "rust-1.66.1" = expr; }
# into
#    { "rust-1.66.1" = expr;
#      rust-1 = { "66" = { "1" = expr; }; };
#    }
```

2023-03-10 05:21 UTC, angerman requested changes
I don't think this PR should contain the

- .editorconfig
- .envrc
- .gitignore

changes. They are orthogonal to the addition of rust support.

2023-03-10 15:05 UTC, yvan-sraka commented
> I don't think this PR should contain the
> 
> * .editorconfig
> * .envrc
> * .gitignore
> 
> changes. They are orthogonal to the addition of rust support.

Do I open one PR by extra config file, are rather make a bulk one with all these little tweaks?

2023-03-10 23:21 UTC, angerman commented
> > I don't think this PR should contain the
> 
> > 
> 
> > * .editorconfig
> 
> > * .envrc
> 
> > * .gitignore
> 
> > 
> 
> > changes. They are orthogonal to the addition of rust support.
> 
> 
> 
> Do I open one PR by extra config file, are rather make a bulk one with all these little tweaks?

Let's have a different PR with those and discuss the merits of adding them or not there.

2023-03-13 08:20 UTC, yvan-sraka commented
> Let's have a different PR with those and discuss the merits of adding them or not there.

https://github.com/input-output-hk/devx/pull/27 :)

2023-03-17 04:21 UTC, angerman commented
@yvan-sraka please rebase this, clean it up, and let's get this merged.

2024-03-13 15:53 UTC, yvan-sraka commented on rust.nix
> +  rust-versions = [
The Rust versions list should be updated!

2024-06-13 18:25 UTC, closed without merging